"""Add description

Revision ID: 49367a22b507
Revises: 
Create Date: 2021-06-12 13:01:41.666716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49367a22b507'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BookDetail', sa.Column('Description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BookDetail', 'Description')
    # ### end Alembic commands ###
