"""add created_date with default value to Empoyee

Revision ID: 5867629bf749
Revises: dff2171f8b62
Create Date: 2021-06-13 19:32:22.223182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5867629bf749'
down_revision = 'dff2171f8b62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Employee', schema=None) as batch_op:
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
