"""remove constraints for examples

Revision ID: cd496010379c
Revises: 5867629bf749
Create Date: 2021-06-13 23:55:49.317302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd496010379c'
down_revision = '5867629bf749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Book', schema=None) as batch_op:
        batch_op.drop_index('ix_Book_ISBN')

    with op.batch_alter_table('Employee', schema=None) as batch_op:
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('Book', schema=None) as batch_op:
        batch_op.create_index('ix_Book_ISBN', ['ISBN'], unique=False)

    # ### end Alembic commands ###
