"""create index for Employee last_name and first_name

Revision ID: dff2171f8b62
Revises: e4887a8bedc7
Create Date: 2021-06-13 19:19:46.362176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff2171f8b62'
down_revision = 'e4887a8bedc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Employee', schema=None) as batch_op:
        batch_op.create_index('my_index', ['LastName', 'FirstName'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Employee', schema=None) as batch_op:
        batch_op.drop_index('my_index')

    # ### end Alembic commands ###
