"""add index to Publisher.Name

Revision ID: e4887a8bedc7
Revises: e7be9204aa67
Create Date: 2021-06-13 19:08:38.514358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4887a8bedc7'
down_revision = 'e7be9204aa67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Publisher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Publisher_Name'), ['Name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Publisher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Publisher_Name'))

    # ### end Alembic commands ###
